[phases.setup]
cmds = ["apt-get update", "apt-get install -y dotnet-sdk-8.0"]

[phases.build]
cmds = ["dotnet publish -c Release -o bin/Release/net8.0/publish"]

[phases.start]
cmd = "dotnet bin/Release/net8.0/publish/用户登录系统.dll"